import os, sys, tempfile, pytest, jwt, json
from web.config import TestingConfig, config
from web import app, db
from datetime import datetime, timedelta

sys.path.append(os.path.dirname(__file__))

def registration(client, username, email, password, password_confirm, instagram_username, instagram_password):
    # action: registration used for the tests
    return client.post(
        '/register',
        data=dict(
                username=username, 
                email=email,
                password=password, 
                password_confirm=password_confirm, 
                instagram_username=instagram_username,
                instagram_password=instagram_password
        ),
        follow_redirects=True)

def login(client, email, password):
    # action: login used for the tests
    return client.post(
        '/login',
        data=dict(email=email, password=password),
        follow_redirects=True)

def reset(client, email):
    return client.post('/reset', data=dict(
        email=email
    ), follow_redirects=True)

def reset_email_token_mock(client, username, email):
    # generate token and return it
    now = str(datetime.now())
    print('-->', os.getenv('SECRET_KEY'))
    encoded_jwt = jwt.encode({"email": email, "datetime": now}, os.getenv('SECRET_KEY'), algorithm="HS256")
    return encoded_jwt

def reset_token(client, token, new_password, new_password2):
    return client.post('/reset/token/'+str(token), data=dict(
        new_password=new_password,
        new_password2=new_password2
    ), follow_redirects=True)

@pytest.fixture
def client():
    db_fd, app.config['DATABASE'] = tempfile.mkstemp()
    app.config.from_object(config[os.getenv('FLASK_ENV')])
    client = app.test_client()

    yield client

    os.close(db_fd)
    os.unlink(app.config['DATABASE'])


def test_resetting_password(client):
    """Testing trying to reset password"""
    user1 = registration(client, 'username1', 'sample1@email.com', 'password1', 'password1', 'instagram_username', 'instagram_password')
    reset_ = reset(client, 'sample@email.com')
    assert (b'Email with instructions to reset your password was sent!' in reset_.data)

def test_resetting_password_with_invalid_email(client):
    """Testing reseting password with invalid email"""
    user1 = registration(client, 'username2', 'sample2@email.com', 'password1', 'password1', 'instagram_username', 'instagram_password')
    reset_ = reset(client, 'sample@wrongemail.com')
    # we should see the same thing. We are showing the same messages so it doesn't allow user enumeration
    # through this page
    assert (b'Email with instructions to reset your password was sent!' in reset_.data)

def test_updating_password_with_invalid_token(client):
    """Testing trying to update password with invalid JWT"""
    user1 = registration(client, 'username3', 'sample3@email.com', 'password1', 'password1', 'instagram_username', 'instagram_password')
    reset_ = reset(client, 'sample@email.com')
    reset_token_ = reset_token(client, 'wrong-token', 'asdfasdf1', 'asdfasdf1')
    # trying to reset password with wrong token
    assert (b'Invalid token' in reset_token_.data)

def test_updating_password_without_saving_token_on_db(client):
    """Testing reset password with token that was not saved on DB.
    Token is being generated by our mock function (since originally it should only be sent
    to the user email)
    """
    user1 = registration(client, 'username4', 'sample4@email.com', 'password1', 'password1', 'instagram_username', 'instagram_password')
    reset_token_ = reset_email_token_mock(client, 'username', 'sample@email.com')
    update_password = reset_token(client, reset_token_, 'asdfasdf1', 'asdfasdf1')
    # trying to reset password with email mock and without saving token on DB
    assert (b'Invalid token' in update_password.data)