"""empty message

Revision ID: 01eeaee746b5
Revises: 6ffb859ce1e1
Create Date: 2021-02-28 01:10:13.753014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01eeaee746b5'
down_revision = '6ffb859ce1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reset_token', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reset_token')
    # ### end Alembic commands ###
