"""empty message

Revision ID: 0937e1b99065
Revises: 7e58021be35e
Create Date: 2021-03-10 20:57:08.911766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0937e1b99065'
down_revision = '7e58021be35e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiktok_email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tiktok_password', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tiktok_password')
        batch_op.drop_column('tiktok_email')

    # ### end Alembic commands ###
