"""empty message

Revision ID: 7e58021be35e
Revises: 01eeaee746b5
Create Date: 2021-02-28 01:25:22.894213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e58021be35e'
down_revision = '01eeaee746b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=200), nullable=True))
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=200), nullable=True))
    op.drop_column('user', 'username')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
